/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-AESIm8PpQqIQ-P0cJMvSSmg4Dg1f-s5jvoMicW9oxFropk56rT9pRXXuHvowP8pLIF5YnKQXmCPSuJi1jOdmghwgwkhjgHwJobSxUosH5ZVvVGRIcLSSaEuF",
  "tt": "tt-1-W0Rwn5OgT-1JDiyklsW6DNasjChUCA9eQMsQcvwN41E=",
  "version": "2020-11-20"
}

export default ebconfig;